### ISSUE TITLE
[request] setting allowing slider to go higher than +-10

### ISSUE THREAD

**Issue by offthesky** [azarbayejani/bandcamp-tempo-adjust#3]
really love this addon! ty for this, its super useful. would love to down the road, in the settings or wherever, see an option allowing one to set the slider range to much higher digits, for more creative type use cases :]

**Comment by azarbayejani** [comment]
Hey! Glad you like the add-on.

This is already a feature. You can make it go up to +100% and around -90% (I think it breaks if you go below -90% due to browser limitations). You can change tempo ranges by clicking on the "±10". Take a look at the demo video in the README. 

https://user-images.githubusercontent.com/241079/207227186-d3f913aa-ea38-4fab-a735-57bb3d71b8fb.mp4

**Comment by offthesky** [comment]
amazing, thank you!!!
