### ISSUE TITLE
Extension not loading on albums that are pre-orders

### ISSUE THREAD

**Issue by bankie606** [azarbayejani/bandcamp-tempo-adjust#7]
Heya I'm noticing that the extension isn't loading on some albums, it looks like when they are set up to be digital pre-orders:

https://analogicalforce.bandcamp.com/album/af047-new-ireland-chrome-ep

https://wrwtfww.com/track/emotion-engine

**Comment by azarbayejani** [comment]
Hey - thanks for the report!

Unfortunately, the extension doesn't work at all on Bandcamp pages that use custom domains (the second link). The reason this limitation exists is because it only requests access to be able to run on *.bandcamp.com domains. I am probably not going to change the permissions to be broader, as it would require running the extension on every page you visit, even if it is not a Bandcamp page. I also don't want to spook people by requesting such a broad permission.

I'll take a look into why this isn't working on pre-orders for *.bandcamp.com though!

**Comment by bankie606** [comment]
Gotcha about the domain thing, i didn't even look at the URL.🫢

**Comment by azarbayejani** [comment]
Fixed the bug. Will test and release to extension this week or next!

Thanks again for the report, Frankie! :)
